package threat

import "github.com/jasonsoprovich/pq-companion/backend/internal/db"

// SPA (spell-effect) codes relevant to hate generation, matching the
// SpellEffect IDs stored in spells_new and labelled in internal/db/enums.
// These follow the EQMacEmu/Server numbering (the fork Project Quarm runs).
const (
	// spaInstantHate (SE_InstantHate) is a flat hate add/subtract applied when
	// the spell lands, stored as the effect's base value. Positive for hate
	// gainers (Terror line: +200..+510) and negative for aggro shedders
	// (Jolt -500, Concussion -400). This is the one hate component that is
	// exactly recoverable from our spell DB with no formula, so it's the basis
	// of the phase-1 spell model.
	spaInstantHate = 92
)

// SpellSource is the narrow slice of the game DB the calculator needs: looking
// up a spell row by its exact name (the form that appears in a "You begin
// casting <Name>" log line). Backed by *db.DB in production; an interface so
// the calculator can be unit-tested without a database.
type SpellSource interface {
	GetSpellByExactName(name string) (*db.Spell, error)
}

// Calculator converts a cast spell into the hate it generates beyond any
// damage it deals. Damage-based hate is intentionally NOT computed here — it is
// observed directly from the character's damage log lines (one point of hate
// per point of damage), so folding it in here too would double-count it. This
// type only answers "how much EXTRA hate did casting this spell add", which for
// phase 1 is its SE_InstantHate component.
type Calculator struct {
	spells SpellSource
}

// NewCalculator returns a Calculator backed by the given spell source. Passing
// a nil source yields a calculator whose CastHate always reports "no data" —
// the tracker then degrades to damage-only hate, which is still useful.
func NewCalculator(spells SpellSource) *Calculator {
	return &Calculator{spells: spells}
}

// CastHate returns the non-damage hate generated by casting spellName, and
// whether the spell was found. The value is signed: aggro-shedding spells
// (Jolt, Concussion) return a negative number so the tracker can drop the
// running total, which is the whole point of those spells for the classes that
// keep dying to aggro.
//
// Phase-1 scope: only the SE_InstantHate (92) component is summed. The larger
// "standard hate" formula for no-damage control/debuff spells (mez, slow,
// tashan — scaled to the mob's max HP) is deferred to a later phase; until then
// those spells contribute only whatever instant hate they carry (usually none).
func (c *Calculator) CastHate(spellName string) (hate int64, found bool) {
	if c == nil || c.spells == nil || spellName == "" {
		return 0, false
	}
	sp, err := c.spells.GetSpellByExactName(spellName)
	if err != nil || sp == nil {
		return 0, false
	}
	for i := 0; i < len(sp.EffectIDs); i++ {
		if sp.EffectIDs[i] == spaInstantHate {
			hate += int64(sp.EffectBaseValues[i])
		}
	}
	return hate, true
}
