package db

import (
	_ "embed"
	"encoding/json"
	"log/slog"
	"strings"
	"sync"
)

// quest_sources.json is generated by cmd/quest-sources from the Project Quarm
// quest scripts (Lua/Perl). It records, per quest-giving NPC, which item IDs
// the NPC rewards and which it requires as turn-ins, tagged with the NPC's
// zone. EQEmu implements quests in scripts rather than DB tables, so this is
// the only source of truth for quest-reward items — quarm.db has no row for
// them. Generated facts (ids/zone/npc) only; lives outside the SQLite dump so
// it survives every quarm.db regeneration from upstream MySQL.
//
//go:embed quest_sources.json
var questSourcesJSON []byte

// QuestFactionDelta is one exact faction adjustment a dialogue branch
// applies — pulled from the quest script's own `e.other:Faction(e.self,
// factionID, delta)` call, the one place a numeric faction amount exists at
// all (the in-game log only ever prints direction). Mirrors the generator's
// schema.
type QuestFactionDelta struct {
	FactionID int `json:"faction_id"`
	Delta     int `json:"delta"`
}

// QuestDialogue is one conditional branch of an NPC's quest handlers: the
// player action that triggers it (Triggers = say keywords, TurnIn = items
// handed over; both empty = an unconditional/hail response), the NPC's spoken
// Text, any items it Grants, and any faction standing it adjusts. Mirrors the
// generator's schema.
type QuestDialogue struct {
	Triggers []string            `json:"triggers,omitempty"`
	TurnIn   []int               `json:"turnin,omitempty"`
	Text     string              `json:"text,omitempty"`
	Grants   []int               `json:"grants,omitempty"`
	Factions []QuestFactionDelta `json:"factions,omitempty"`
}

// QuestEntry is one NPC's quest activity. Mirrors the generator's schema.
type QuestEntry struct {
	Zone     string          `json:"zone"`
	NPC      string          `json:"npc"`
	Rewards  []int           `json:"rewards,omitempty"`
	TurnIns  []int           `json:"turnins,omitempty"`
	Dialogue []QuestDialogue `json:"dialogue,omitempty"`
}

var (
	questOnce          sync.Once
	questEntries       []QuestEntry
	questByReward      map[int][]*QuestEntry
	questByTurnIn      map[int][]*QuestEntry
	questRewardZoneSet map[int]map[string]bool
	questDialogueByNPC map[string][]*QuestDialogue
)

// loadQuestSources parses the embedded quest_sources.json once and builds the
// item→quest indexes. On a parse error it installs empty indexes (degrades to
// "no quest sources known") rather than failing.
func loadQuestSources() {
	questOnce.Do(func() {
		if err := json.Unmarshal(questSourcesJSON, &questEntries); err != nil {
			slog.Error("parse quest_sources.json", "err", err)
			questEntries = nil
		}
		questByReward = make(map[int][]*QuestEntry)
		questByTurnIn = make(map[int][]*QuestEntry)
		questRewardZoneSet = make(map[int]map[string]bool)
		questDialogueByNPC = make(map[string][]*QuestDialogue)
		for i := range questEntries {
			e := &questEntries[i]
			for _, id := range e.Rewards {
				questByReward[id] = append(questByReward[id], e)
				if questRewardZoneSet[id] == nil {
					questRewardZoneSet[id] = map[string]bool{}
				}
				questRewardZoneSet[id][e.Zone] = true
			}
			for _, id := range e.TurnIns {
				questByTurnIn[id] = append(questByTurnIn[id], e)
			}
			key := strings.ToLower(e.NPC)
			for j := range e.Dialogue {
				b := &e.Dialogue[j]
				if len(b.Factions) > 0 {
					questDialogueByNPC[key] = append(questDialogueByNPC[key], b)
				}
			}
		}
	})
}

// ResolveQuestFactionDialogue matches an NPC's spoken log line (from
// EventNPCDialogue) against that NPC's quest-script dialogue branches,
// returning the exact faction deltas the matched branch applies. sayText is
// matched as a case-insensitive substring of a branch's stored Text — EQ logs
// one "<NPC> says, '...'" line per script Say() call, while a branch's Text
// may concatenate several, so containment (not equality) is the right test.
// Returns ok=false when the NPC has no faction-bearing dialogue at all, or
// none of it matches sayText — the common case for the vast majority of
// ordinary NPC hails and all non-quest chat.
func ResolveQuestFactionDialogue(npcName, sayText string) ([]QuestFactionDelta, bool) {
	loadQuestSources()
	branches := questDialogueByNPC[strings.ToLower(npcName)]
	if len(branches) == 0 {
		return nil, false
	}
	needle := strings.ToLower(strings.TrimSpace(sayText))
	if needle == "" {
		return nil, false
	}
	for _, b := range branches {
		if strings.Contains(strings.ToLower(b.Text), needle) {
			return b.Factions, true
		}
	}
	return nil, false
}

// questRewardZones returns the distinct zone short-names in which an item is a
// quest reward. Used by the PoP/era classifier to give quest-reward items a
// source zone (they have no drop/vendor/forage row).
func questRewardZones(itemID int) []string {
	loadQuestSources()
	set := questRewardZoneSet[itemID]
	if len(set) == 0 {
		return nil
	}
	zones := make([]string, 0, len(set))
	for z := range set {
		zones = append(zones, z)
	}
	return zones
}

// QuestsForItem returns the quests that reward the item and the quests that
// require it as a turn-in. Backs the item page's Quests tab.
func QuestsForItem(itemID int) (rewardedBy, usedIn []QuestEntry) {
	loadQuestSources()
	for _, e := range questByReward[itemID] {
		rewardedBy = append(rewardedBy, *e)
	}
	for _, e := range questByTurnIn[itemID] {
		usedIn = append(usedIn, *e)
	}
	return rewardedBy, usedIn
}
