package db

import (
	_ "embed"
	"encoding/json"
	"log/slog"
	"sync"
)

// quest_sources.json is generated by cmd/quest-sources from the Project Quarm
// quest scripts (Lua/Perl). It records, per quest-giving NPC, which item IDs
// the NPC rewards and which it requires as turn-ins, tagged with the NPC's
// zone. EQEmu implements quests in scripts rather than DB tables, so this is
// the only source of truth for quest-reward items — quarm.db has no row for
// them. Generated facts (ids/zone/npc) only; lives outside the SQLite dump so
// it survives every quarm.db regeneration from upstream MySQL.
//
//go:embed quest_sources.json
var questSourcesJSON []byte

// QuestEntry is one NPC's quest item activity. Mirrors the generator's schema.
type QuestEntry struct {
	Zone    string `json:"zone"`
	NPC     string `json:"npc"`
	Rewards []int  `json:"rewards,omitempty"`
	TurnIns []int  `json:"turnins,omitempty"`
}

var (
	questOnce          sync.Once
	questEntries       []QuestEntry
	questByReward      map[int][]*QuestEntry
	questByTurnIn      map[int][]*QuestEntry
	questRewardZoneSet map[int]map[string]bool
)

// loadQuestSources parses the embedded quest_sources.json once and builds the
// item→quest indexes. On a parse error it installs empty indexes (degrades to
// "no quest sources known") rather than failing.
func loadQuestSources() {
	questOnce.Do(func() {
		if err := json.Unmarshal(questSourcesJSON, &questEntries); err != nil {
			slog.Error("parse quest_sources.json", "err", err)
			questEntries = nil
		}
		questByReward = make(map[int][]*QuestEntry)
		questByTurnIn = make(map[int][]*QuestEntry)
		questRewardZoneSet = make(map[int]map[string]bool)
		for i := range questEntries {
			e := &questEntries[i]
			for _, id := range e.Rewards {
				questByReward[id] = append(questByReward[id], e)
				if questRewardZoneSet[id] == nil {
					questRewardZoneSet[id] = map[string]bool{}
				}
				questRewardZoneSet[id][e.Zone] = true
			}
			for _, id := range e.TurnIns {
				questByTurnIn[id] = append(questByTurnIn[id], e)
			}
		}
	})
}

// questRewardZones returns the distinct zone short-names in which an item is a
// quest reward. Used by the PoP/era classifier to give quest-reward items a
// source zone (they have no drop/vendor/forage row).
func questRewardZones(itemID int) []string {
	loadQuestSources()
	set := questRewardZoneSet[itemID]
	if len(set) == 0 {
		return nil
	}
	zones := make([]string, 0, len(set))
	for z := range set {
		zones = append(zones, z)
	}
	return zones
}

// QuestsForItem returns the quests that reward the item and the quests that
// require it as a turn-in. Backs the item page's Quests tab.
func QuestsForItem(itemID int) (rewardedBy, usedIn []QuestEntry) {
	loadQuestSources()
	for _, e := range questByReward[itemID] {
		rewardedBy = append(rewardedBy, *e)
	}
	for _, e := range questByTurnIn[itemID] {
		usedIn = append(usedIn, *e)
	}
	return rewardedBy, usedIn
}
