package db

import (
	_ "embed"
	"encoding/json"
	"log/slog"
	"sync"
)

// quest_sources.json is generated by cmd/quest-sources from the Project Quarm
// quest scripts (Lua/Perl). It records, per quest-giving NPC, which item IDs
// the NPC rewards and which it requires as turn-ins, tagged with the NPC's
// zone. EQEmu implements quests in scripts rather than DB tables, so this is
// the only source of truth for quest-reward items — quarm.db has no row for
// them. Generated facts (ids/zone/npc) only; lives outside the SQLite dump so
// it survives every quarm.db regeneration from upstream MySQL.
//
//go:embed quest_sources.json
var questSourcesJSON []byte

// QuestStep is one turn-in→reward exchange at an NPC. Requires is empty for a
// reward granted without a turn-in (a quest-start item handed out in dialogue).
type QuestStep struct {
	Requires []int `json:"requires,omitempty"`
	Grants   []int `json:"grants,omitempty"`
}

// QuestEntry is one NPC's quest item activity. Mirrors the generator's schema.
type QuestEntry struct {
	Zone    string      `json:"zone"`
	NPC     string      `json:"npc"`
	Rewards []int       `json:"rewards,omitempty"`
	TurnIns []int       `json:"turnins,omitempty"`
	Steps   []QuestStep `json:"steps,omitempty"`
}

// stepLoc points at one step within one NPC's entry, for the chain graph.
type stepLoc struct {
	entry *QuestEntry
	step  *QuestStep
}

// QuestChainNode is one reconstructed step in an item's questline (unresolved
// item ids; the API layer resolves names). Ordered prerequisite-first.
type QuestChainNode struct {
	Zone     string
	NPC      string
	Requires []int
	Grants   []int
}

var (
	questOnce          sync.Once
	questEntries       []QuestEntry
	questByReward      map[int][]*QuestEntry
	questByTurnIn      map[int][]*QuestEntry
	questRewardZoneSet map[int]map[string]bool
	stepsByGrant       map[int][]stepLoc
)

// loadQuestSources parses the embedded quest_sources.json once and builds the
// item→quest indexes. On a parse error it installs empty indexes (degrades to
// "no quest sources known") rather than failing.
func loadQuestSources() {
	questOnce.Do(func() {
		if err := json.Unmarshal(questSourcesJSON, &questEntries); err != nil {
			slog.Error("parse quest_sources.json", "err", err)
			questEntries = nil
		}
		questByReward = make(map[int][]*QuestEntry)
		questByTurnIn = make(map[int][]*QuestEntry)
		questRewardZoneSet = make(map[int]map[string]bool)
		stepsByGrant = make(map[int][]stepLoc)
		for i := range questEntries {
			e := &questEntries[i]
			for _, id := range e.Rewards {
				questByReward[id] = append(questByReward[id], e)
				if questRewardZoneSet[id] == nil {
					questRewardZoneSet[id] = map[string]bool{}
				}
				questRewardZoneSet[id][e.Zone] = true
			}
			for _, id := range e.TurnIns {
				questByTurnIn[id] = append(questByTurnIn[id], e)
			}
			for j := range e.Steps {
				s := &e.Steps[j]
				for _, id := range s.Grants {
					stepsByGrant[id] = append(stepsByGrant[id], stepLoc{entry: e, step: s})
				}
			}
		}
	})
}

// maxChainSteps bounds chain reconstruction so a pathological item-flow graph
// (cycles, hub items required by dozens of quests) can't blow up the response.
const maxChainSteps = 30

// QuestChainForItem reconstructs the questline that yields an item: the steps
// that grant it, plus the prerequisite steps that produce the items those
// steps require, transitively. Steps are returned prerequisite-first (a step
// producing item X precedes a step that requires X). Items required but not
// produced by any step (drops, combines, base items) are left as Requires on
// their step so the caller can link them to their own pages.
func QuestChainForItem(itemID int) []QuestChainNode {
	loadQuestSources()
	if len(stepsByGrant[itemID]) == 0 {
		return nil
	}

	// Collect the dependency closure of steps via BFS over required items.
	seenStep := map[stepLoc]bool{}
	var closure []stepLoc
	queue := []int{itemID}
	queued := map[int]bool{itemID: true}
	for len(queue) > 0 && len(closure) < maxChainSteps {
		item := queue[0]
		queue = queue[1:]
		for _, loc := range stepsByGrant[item] {
			if seenStep[loc] {
				continue
			}
			seenStep[loc] = true
			closure = append(closure, loc)
			for _, req := range loc.step.Requires {
				if !queued[req] {
					queued[req] = true
					queue = append(queue, req)
				}
			}
			if len(closure) >= maxChainSteps {
				break
			}
		}
	}

	// Which items are produced by some step in the closure — used to decide
	// when a step's requirements are satisfied for topological ordering.
	producedInClosure := map[int]bool{}
	for _, loc := range closure {
		for _, g := range loc.step.Grants {
			producedInClosure[g] = true
		}
	}

	// Topological sort: emit a step once every requirement it needs that is
	// produced within the closure has already been emitted. Requirements that
	// are NOT produced in the closure (leaf items) don't block emission.
	emitted := map[int]bool{}
	remaining := append([]stepLoc(nil), closure...)
	var ordered []QuestChainNode
	for len(remaining) > 0 {
		progressed := false
		next := remaining[:0]
		for _, loc := range remaining {
			ready := true
			for _, req := range loc.step.Requires {
				if producedInClosure[req] && !emitted[req] {
					ready = false
					break
				}
			}
			if !ready {
				next = append(next, loc)
				continue
			}
			ordered = append(ordered, QuestChainNode{
				Zone:     loc.entry.Zone,
				NPC:      loc.entry.NPC,
				Requires: loc.step.Requires,
				Grants:   loc.step.Grants,
			})
			for _, g := range loc.step.Grants {
				emitted[g] = true
			}
			progressed = true
		}
		remaining = next
		if !progressed {
			// Cycle — emit the rest in arbitrary order rather than loop forever.
			for _, loc := range remaining {
				ordered = append(ordered, QuestChainNode{
					Zone:     loc.entry.Zone,
					NPC:      loc.entry.NPC,
					Requires: loc.step.Requires,
					Grants:   loc.step.Grants,
				})
			}
			break
		}
	}
	return ordered
}

// questRewardZones returns the distinct zone short-names in which an item is a
// quest reward. Used by the PoP/era classifier to give quest-reward items a
// source zone (they have no drop/vendor/forage row).
func questRewardZones(itemID int) []string {
	loadQuestSources()
	set := questRewardZoneSet[itemID]
	if len(set) == 0 {
		return nil
	}
	zones := make([]string, 0, len(set))
	for z := range set {
		zones = append(zones, z)
	}
	return zones
}

// QuestsForItem returns the quests that reward the item and the quests that
// require it as a turn-in. Backs the item page's Quests tab.
func QuestsForItem(itemID int) (rewardedBy, usedIn []QuestEntry) {
	loadQuestSources()
	for _, e := range questByReward[itemID] {
		rewardedBy = append(rewardedBy, *e)
	}
	for _, e := range questByTurnIn[itemID] {
		usedIn = append(usedIn, *e)
	}
	return rewardedBy, usedIn
}
