package db

// zoneCatalog is the curated set of zones surfaced in the zone browser,
// each mapped to its canonical expansion bucket. Sourced from
// https://www.pqdi.cc/zones — Project Quarm's reference site for active
// game zones.
//
// The value is the displayed expansion ID:
//
//	0 = Classic
//	1 = Ruins of Kunark
//	2 = Scars of Velious
//	3 = Shadows of Luclin
//	4 = Planes of Power
//
// We override the raw zone.expansion column because EQMacEmu's schema uses
// that field as a content-tuning bucket rather than "introduced in"; many
// Classic dungeons (fearplane, hateplane, mistmoore, unrest, crushbone,
// gukbottom, kedge) and Kunark dungeons (karnor, sebilis, charasis) ship
// with expansion=3 in the upstream DB even though players (and PQDI) group
// them by their original release era. The map keys also serve as the
// visibility allowlist — any zone not listed is hidden (test stubs,
// alternate clones, dev zones, etc.).
var zoneCatalog = map[string]int{
	// Classic
	"akanon":         0,
	"airplane":       0,
	"air_instanced":  0,
	"arena":          0,
	"befallen":       0,
	"beholder":       0,
	"blackburrow":    0,
	"butcher":        0,
	"cauldron":       0,
	"cazicthule":     0,
	"cazicthule_old": 0,
	"commons":        0,
	"crushbone":      0,
	"cshome":         0,
	"eastkarana":     0,
	"ecommons":       0,
	"erudnext":       0,
	"erudnint":       0,
	"erudsxing":      0,
	"everfrost":      0,
	"fearplane":      0,
	"fear_instanced": 0,
	"feerrott":       0,
	"felwithea":      0,
	"felwitheb":      0,
	"freporte":       0,
	"freportn":       0,
	"freportw":       0,
	"gfaydark":       0,
	"grobb":          0,
	"gukbottom":      0,
	"guktop":         0,
	"halas":          0,
	"hateplane":      0,
	"hate_instanced": 0,
	"highkeep":       0,
	"highpass":       0,
	"hole_instanced": 0,
	"innothule":      0,
	"kaladima":       0,
	"kaladimb":       0,
	"kedge":          0,
	"kerraridge":     0,
	"kithicor":       0,
	"lakerathe":      0,
	"lavastorm":      0,
	"lfaydark":       0,
	"misty":          0,
	"mistmoore":      0,
	"najena":         0,
	"nektulos":       0,
	"neriaka":        0,
	"neriakb":        0,
	"neriakc":        0,
	"northkarana":    0,
	"nro":            0,
	"oasis":          0,
	"oggok":          0,
	"oot":            0,
	"paineel":        0,
	"paw":            0,
	"permafrost":     0,
	"qcat":           0,
	"qey2hh1":        0,
	"qeynos":         0,
	"qeynos2":        0,
	"qeytoqrg":       0,
	"qrg":            0,
	"rathemtn":       0,
	"rivervale":      0,
	"runnyeye":       0,
	"soldunga":       0,
	"soldungb":       0,
	"soltemple":      0,
	"southkarana":    0,
	"sro":            0,
	"steamfont":      0,
	"tox":            0,
	"unrest":         0,

	// Kunark
	"burningwood":   1,
	"cabeast":       1,
	"cabwest":       1,
	"chardok":       1,
	"charasis":      1,
	"citymist":      1,
	"dalnir":        1,
	"dreadlands":    1,
	"droga":         1,
	"emeraldjungle": 1,
	"fieldofbone":   1,
	"firiona":       1,
	"frontiermtns":  1,
	"hole":          1,
	"kaesora":       1,
	"karnor":        1,
	"kurn":          1,
	"lakeofillomen": 1,
	"nurga":         1,
	"overthere":     1,
	"sebilis":       1,
	"skyfire":       1,
	"swampofnohope": 1,
	"timorous":      1,
	"towerfrost":    1,
	"trakanon":      1,
	"veeshan":       1,
	"veksar":        1,
	"warslikswood":  1,

	// Velious
	"cobaltscar":    2,
	"crystal":       2,
	"eastwastes":    2,
	"frozenshadow":  2,
	"greatdivide":   2,
	"growthplane":   2,
	"iceclad":       2,
	"kael":          2,
	"mischiefplane": 2,
	"necropolis":    2,
	"sirens":        2,
	"skyshrine":     2,
	"sleeper":       2,
	"stonebrunt":    2,
	"templeveeshan": 2,
	"thurgadina":    2,
	"thurgadinb":    2,
	"velketor":      2,
	"wakening":      2,
	"warrens":       2,
	"westwastes":    2,

	// Luclin
	"acrylia":     3,
	"akheva":      3,
	"bazaar":      3,
	"dawnshroud":  3,
	"echo":        3,
	"fungusgrove": 3,
	"griegsend":   3,
	"grimling":    3,
	"hollowshade": 3,
	"jaggedpine":  3,
	"katta":       3,
	"letalis":     3,
	"maiden":      3,
	"mseru":       3,
	"netherbian":  3,
	"nexus":       3,
	"paludal":     3,
	"scarlet":     3,
	"shadeweaver": 3,
	"shadowhaven": 3,
	"sharvahl":    3,
	"ssratemple":  3,
	"sseru":       3,
	"tenebrous":   3,
	"thedeep":     3,
	"thegrey":     3,
	"twilight":    3,
	"umbral":      3,
	"vexthal":     3,

	// Planes of Power
	"bothunder":     4,
	"codecay":       4,
	"hohonora":      4,
	"hohonorb":      4,
	"nightmareb":    4,
	"poair":         4,
	"podisease":     4,
	"poeartha":      4,
	"poearthb":      4,
	"pofire":        4,
	"poinnovation":  4,
	"pojustice":     4,
	"poknowledge":   4,
	"ponightmare":   4,
	"postorms":      4,
	"potactics":     4,
	"potimea":       4,
	"potimeb":       4,
	"potorment":     4,
	"potranquility": 4,
	"povalor":       4,
	"powater":       4,
	"solrotower":    4,
}
